name: Build and Deploy

on:
  push:
    branches: [ master ]
  
env: 
  PUBLISH_PATH: "."
  DOTNET_VERSION: "6.0.X"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the code
      uses: action/checkout@master
    - name: set up dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${ env.DOTNET_VERSION }
    - name: install dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --configuration Release --no-restore
    - name: publish
      run: dotnet publish --configuration Release -o '${{ env.PUBLISH_PATH }}'/publish